### ISSUE TITLE
Configure all scripts to use siteinfo instead of mlabconfig.py

### ISSUE THREAD

**Issue by nkinkade** [m-lab/epoxy-images#120]
Currently, the `setup_stage1.sh` script uses mlabconfig.py to get a list of nodes and their IP addresses. mlabconfig.py uses the old PLC-based file sites.py, and we want to move away from using sites.py and to start using [siteinfo](https://github.com/m-lab/siteinfo), or some API which is backed by siteinfo.

At least this one location will need updating, and perhaps more (?):

https://github.com/m-lab/epoxy-images/blob/master/setup_stage1_isos.sh#L22

**Comment by nkinkade** [comment]
@stephen-soltesz: Was this issue resolved?

**Comment by stephen-soltesz** [comment]
Yes? mlabconfig reads from siteinfo now. So, users of mlabconfig are sourcing it instead of sites.py.

Does that sound right to you?

**Comment by nkinkade** [comment]
It does, sorry. I guess it's nearly hardwired into my head that mlabconfig==sites.py==legacystuff.
