### ISSUE TITLE
stage1 images should have a fall-back login mechanism

### ISSUE THREAD

**Issue by nkinkade** [m-lab/epoxy-images#142]
Today, on the legacy PLC platform, if a node fails to boot fully to PLC for some reason the node will fall-back to "SafeBoot" mode, allowing an operator or PLC admin to login to inspect the issue. However, our ePoxy stage1 images don't have this facility, though it does appear that it [occurred to @stephen-soltesz when developing ePoxy](https://github.com/m-lab/epoxy-images/blob/master/setup_stage1_minimal.sh#L160).

One use case for this feature is if ePoxy boot fails for any reason, an operator can fix the issue with ePoxy, login to the machine and reboot it. Generally the reboot could be done via the DRAC, but at new sites the DRAC may not yet have been configured. This is probably another good use case for [configuring DRAC basics during stage1 boot](https://github.com/m-lab/epoxy-images/issues/134).

**Comment by nkinkade** [comment]
@robertodauria: This was closed, but I don't see any PRs or code changes in epoxy-images that would resolve this. Was this resolved in some way that I'm not seeing, or perhaps it was decided we don't need it?

**Comment by robertodauria** [comment]
Definitely a mistake. I've [added retry logic to epoxy_client](https://github.com/m-lab/epoxy/pull/90) but have not added any way to log into stage1 remotely
