### ISSUE TITLE
fix-hung-shim.sh must recognize multiple shim processes

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy-images#159]
Recently a rollout of the host DS stalled for multiple days b/c several machines had 2 containers hung during shutdown. Currently, fix-hung-shim.sh expects only a single shim process to hang. It needs to detect multiple hung shim processes.

![host-stall](https://user-images.githubusercontent.com/1085316/71374419-95f71780-2588-11ea-8c14-47a25b62680e.png)

For example:
```
$ docker ps | grep host
06ee5a8d016e        e4c310f63d8a    "/traceroute-caller …"   13 days ago         Up 13 days                              k8s_traceroute_host-cpzdj_default_dd0c6aab-3dbb-44aa-8ea1-3dd6fd2bf299_0
e38f71d2de57        c478ac8aa02b    "/bin/tcp-info -prom…"   13 days ago         Up 13 days                              k8s_tcpinfo_host-cpzdj_default_dd0c6aab-3dbb-44aa-8ea1-3dd6fd2bf299_0
```

**Comment by nkinkade** [comment]
This should have been fixed by merged PR #160. Closing.
