### ISSUE TITLE
Unpin linux-source-4.4.0 version

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy-images#16]
The latest linux-source versions 4.4.0-109.132 and 4.4.0-108.131 do not build.

The cause appears to be fixed according to the [ChangeLog in 4.4.111](https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.4.111)

However, that version is not yet available in xenial packages. So, temporarily, we will pin the linux-source-4.4.0 version to 4.4.0-104.127

**Comment by nkinkade** [comment]
I believe this issue is no longer relevant now that we are using stock Ubuntu. @stephen-soltesz: if you believe this to be true, would you close this issue?

**Comment by stephen-soltesz** [comment]
There may be some relationship between the `MFT_VERSION` (Mellanox firmware tools) and the kernel. But that is not cited here.
