### ISSUE TITLE
Disable "dynamic MOTD" when logging in via SSH

### ISSUE THREAD

**Issue by robertodauria** [m-lab/epoxy-images#184]

**Comment by nkinkade** [comment]
Looks like this can be done with something like the following in the image build script:

```
chmod -x /etc/update-motd.d/*
```

**Comment by robertodauria** [comment]
I'm currently testing a solution with 
```
sed -i -e 's/ENABLED=1/ENABLED=0/g' $BOOTSTRAP/etc/default/motd-news
```

stage3 images [are still being built](https://console.cloud.google.com/cloud-build/builds/11932795-71f3-4ce5-8e39-af91b842ffb9?authuser=1&project=mlab-sandbox)

**Comment by nkinkade** [comment]
Does that only disable the "news" part of the motd, but leaving all the other stuff?

**Comment by robertodauria** [comment]
That's correct, it should not contact the Canonical servers to fetch the news anymore (the annoying part, I believe.)
