### ISSUE TITLE
Create versioned stage3 images and URLs

### ISSUE THREAD

**Issue by nkinkade** [m-lab/epoxy-images#202]
In a discussion with @stephen-soltesz today, we realized that deployment of stage3 images into production is currently condensed into a single, non-versioned step, but should probably be two.

Currently, when the epoxy-images repository is tagged, new stage1 and stage3 images are built and published to static, non-versioned locations in GCS. This means that the URL for images never changes, while the underlying file that backs the URL does. This can lead to confusion about what is actually being deployed and booting at any given time.

We should probably implement versioned stage3 image URLs, such that tagging epoxy-images builds versioned images (and URLs), and then a second step would be required to cause them to be deployed. That second step would be to somehow modify the GCD entity for every node to point to the new versioned URL.

**Comment by stephen-soltesz** [comment]
@nkinkade this came up again this morning.

**Comment by nkinkade** [comment]
This is resolved by PRs:

https://github.com/m-lab/epoxy-images/pull/206
https://github.com/m-lab/epoxy/pull/100
