### ISSUE TITLE
Add project to kernel cmdline

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy-images#42]
Now that ROMs can target epoxy server in different GCP projects, this variable should be accessible during runtime so epoxy_client can automatically fetch images from the correct project buckets.

In particular, the later stage actions should refer to URLs that reference the GCP project.

```
"files" : {
     "vmlinuz" : {
        "url" : "https://storage.googleapis.com/epoxy-{{get_karg `epoxy.project`}}/stage3_coreos/coreos_production_pxe.vmlinuz"
     },
     "initram" : {
        "url" : "https://storage.googleapis.com/epoxy-{{get_karg `epoxy.project`}}/stage3_coreos/coreos_custom_pxe_image.cpio.gz"
     }
 },

```

**Comment by kokosta** [comment]
Done actually.
