### ISSUE TITLE
Configure host IPv6 address

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy-images#89]
Now that index2ip supports IPv6 https://github.com/m-lab/index2ip/pull/10 we should configure the IPv6 host network.

* NOTE: this should be done after epoxy_client completes until the epoxy server has native support for IPv6.

https://github.com/m-lab/epoxy-images/blob/dev/configs/stage3_coreos/resources/generate_network_config.sh

Note, this change should also update to use the `epoxy.ipv4=` and `epoxy.ipv6=` kernel parameters.

**Comment by nkinkade** [comment]
This is done. Closing.
